name: Build
 
on:
    pull_request:
      branches: ["main"]  
 
jobs:
  backstage_validator:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
       - uses: RoadieHQ/backstage-entity-validator@v0.3.11
         with:
           path: 'catalog-info.yaml'